# A Docker Compose must always start with the version tag.
version: '3'

# Docker Compose works with services.
# 1 service = 1 container.
# For example, a server, a client, a database...
# We use the keyword 'services' to start to create services.
services:

  # the name of this serivce(container) is called "app"
  app:
    #the images tells docker what image we are building. but we're gonna use images from the repo.
    image: planetarium
    # the build section provides docker with the details needed to build the specified image
    build:
      # context tells docker where the dockerfile is: . indicates current directory
      context: .
      dockerfile: dockerfile
    # container_name sets the name of the container --simulates adding the --name flag to docker run
    container_name: app
    # ports maps the host port (left side) to the container port (right side)
    ports:
      - 8080:8080
    # depends_on is useful if you need another container to be created first
    #    depends_on:
    #      - dependency
    # you can set environment variables in the container
    environment:
      - VARIABLE=VALUE
    # you can map files in a container directory (right side) to a directory outside the container (left side)
    volumes:
      - ./logs/:/logs/


  # this is the second container for our deployment
#  dependency:
#
#    image: 'anotherImage'
#    container_name: requiredContent
#    ports:
#      - 1234:1234


# docker-compose up -d
# docker-compose down


  docker image ls #lists your images
  
  docker image rm {image name} #deletes a specific image
  
  docker ps # lists all running containers
  
  docker ps -a # lists all containers (running and not running)
  
  docker stop {container name or id} #stops a container
  
  docker rm {container name} #removes the container
  
  docker logs {container name} #shows container STDOUT logs
  
  docker run -p {host-port}:{container-port} {image-name} # add -d if you want to run in detached mode
  
  docker build -t {name} {Dockerfile path} # tells docker to build an image and to assign it the given name
  
  docker-compose up # tells docker to create and run the services designated in a docker-compose.yml file, can run detached
  
  docker-compose down # tells docker to destroy the services designated in a docker-compose.yml file
  
  docker build -t {repo/image name:tag} {dockerfile path}
  
  docker push {repo/image}
  
  docker pull {repo/image?
  
  docker image rm $(docker image ls -q)
  
  docker stop $(docker container ls -q)