apiVersion: v1
kind: Secret  #component
metadata:
  name: mongo-secret  #arbitrary name
type: Opaque
data:  #content
  mongo-user: bW9uZ291c2Vy   #use encode values(see linux/useful-commands.sh)
  mongo-password: bW9uZ29wYXNzd29yZA==  #use encode values(see linux/useful-commands.sh)
